### ISSUE TITLE
Add Durham

### ISSUE THREAD

**Issue by oaksandspokes** [oaksandspokes/raleighbikeways#6]
Add Durham bike infrastructure

**Comment by npdoty** [comment]
Let us know if Durham-ites can help!

**Comment by oaksandspokes** [comment]
@npdoty Thanks for the offer, and you can!  I have added Durham on a [branch](https://github.com/jonathonwpowell/raleighbikeways/tree/durham) which is hosted [here](https://5e100efe8dfaa100080468f8--adoring-wing-48a930.netlify.com/).  Would you mind taking a look to see if I didn't miss / or mislabel anything? 


Also I got the data from [here](https://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fwebgis.durhamnc.gov%2Fserver%2Frest%2Fservices%2FOpenData%2FBike_Facilities%2FMapServer&source=sd), and I wasn't sure which layers to include for the recommended routes.  The "shared roadways" seemed okay but from google mapping it "shared roadways with wide outside lanes" seemed not very comfortable.  I am sure you have a better sense of it than me, what do you think?  My general feeling is that anything over 25-30 without bike infrastructure won't go in the recommended category, but that isn't set in stone. Thanks!

If you have any other ideas let me know :)

**Comment by npdoty** [comment]
Ah, yes, that's the set of layers that's used for the [Durham Bike & Hike Map](https://durhamnc.gov/1031/Durham-Bike-Hike-Map), which is unfortunately a bit out of date -- it doesn't include the only segment of protected bike lane in Durham. 

Residents can more easily keep the OpenStreetMap definitions more up to date ([see the cycle map layer around Durham](https://www.openstreetmap.org/#map=15/35.9955/-78.9061&layers=C), for example), although there isn't an easy way to include a "recommended" path on OSM: for example to map streets without sharrows that are still suggested for biking.

That Hike & Bike Map dataset is perhaps not entirely consistent, but I would largely agree that the "shared roadways with wide outside lanes" both don't have any bike facilities and typically aren't comfortable to ride on because of the speed or amount of car traffic.

I'm also not sure how "bikeway" is being defined for this map. That Durham dataset primarily includes unprotected bike lanes (some with a painted buffer and some without) -- is that the definition you're using for Raleigh as well? I guess it wouldn't be very useful for a current rider, but in the future, I'd hope that bike maps would focus on protected infrastructure that a wider range of riders is comfortable using. OpenStreetMap tags/names that "cycletracks", of which there is only one stretch in Durham, on East Main.

**Comment by jonathonwpowell** [comment]
I think leveraging OSM data for the physical infrastructure is a good one, and maybe mixing it with the city data for recommended paths.  Cities seem to fluctuate on their update timeliness.  Do you want to look into a way to add OSM data updates without any manual effort?  I used https://overpass-turbo.eu/ to get all the infrastructure with the query below, but the API does't return in a data format we can use to my knowledge, it has to be converted manually. Maybe a weekly script or something?

As for the bikeways thing, naming is hard and I plan to clarify it today.  It is supposed to be sidepaths + bike lanes.  And a different color for separated bike infrastructure is a good idea, sadly there isn't much outside the greenways.

```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“cycleway=lane or cycleway=left or cycleway=right or highway=cycleway or bicycle=designated or cycleway:right=* or cycleway:left=*”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “cycleway=lane”
  node["cycleway"="lane"]({{bbox}});
  way["cycleway"="lane"]({{bbox}});
  relation["cycleway"="lane"]({{bbox}});
  // query part for: “cycleway=left”
  node["cycleway"="left"]({{bbox}});
  way["cycleway"="left"]({{bbox}});
  relation["cycleway"="left"]({{bbox}});
  // query part for: “cycleway=right”
  node["cycleway"="right"]({{bbox}});
  way["cycleway"="right"]({{bbox}});
  relation["cycleway"="right"]({{bbox}});
  // query part for: “highway=cycleway”
  node["highway"="cycleway"]({{bbox}});
  way["highway"="cycleway"]({{bbox}});
  relation["highway"="cycleway"]({{bbox}});
  // query part for: “bicycle=designated”
  node["bicycle"="designated"]({{bbox}});
  way["bicycle"="designated"]({{bbox}});
  relation["bicycle"="designated"]({{bbox}});
  // query part for: “"cycleway:right"=*”
  node["cycleway:right"]({{bbox}});
  way["cycleway:right"]({{bbox}});
  relation["cycleway:right"]({{bbox}});
  // query part for: “"cycleway:left"=*”
  node["cycleway:left"]({{bbox}});
  way["cycleway:left"]({{bbox}});
  relation["cycleway:left"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
```

**Comment by npdoty** [comment]
I'll look into it (#23) but if you want to post that city-sourced ArcGIS data, that still sounds helpful in the meantime.

**Comment by oaksandspokes** [comment]
Durham has been added in #24 , closing
